import type { Note } from '../types/note.schema'

const notes: Note[] = [
  {
    id: 'note-001',
    title: 'Project Ideas 2026',
    content: 'Need to brainstorm new AI features for the web app...',
    folder: 'Work',
    tags: ['brainstorming', 'ai', 'planning'],
    isPinned: true,
    isArchived: false,
    syncStatus: 'synced',
    createdAt: new Date('2026-03-20T08:30:00Z'),
    updatedAt: new Date('2026-03-23T10:15:00Z'),
  },
  {
    id: 'note-002',
    title: 'Weekly Groceries',
    content: '- Milk\n- Eggs\n- Spinach\n- Coffee beans',
    folder: 'Personal',
    tags: ['shopping', 'errands'],
    isPinned: false,
    isArchived: false,
    syncStatus: 'synced',
    createdAt: new Date('2026-03-22T14:00:00Z'),
    updatedAt: new Date('2026-03-22T14:05:00Z'),
  },
  {
    id: 'note-003',
    title: 'Meeting with Design Team',
    content:
      'Discussed the new UI mockup. Need to adjust the contrast on the primary buttons.',
    folder: 'Work/Meetings',
    tags: ['meeting', 'design', 'ui'],
    isPinned: false,
    isArchived: false,
    syncStatus: 'syncing',
    createdAt: new Date('2026-03-23T09:00:00Z'),
    updatedAt: new Date('2026-03-23T09:45:00Z'),
  },
  {
    id: 'note-004',
    title: 'Tax Documents 2025',
    content:
      'W2 forms are in the filing cabinet. Need to upload receipts to the portal.',
    folder: 'Finance',
    tags: ['taxes', 'important'],
    isPinned: false,
    isArchived: true,
    syncStatus: 'synced',
    createdAt: new Date('2026-01-15T11:20:00Z'),
    updatedAt: new Date('2026-02-10T16:00:00Z'),
  },
  {
    id: 'note-005',
    title: 'Japan Trip Itinerary',
    content: 'Day 1: Arrive in Tokyo. Day 2: Shibuya and Shinjuku...',
    folder: 'Travel',
    tags: ['japan', 'vacation', 'planning'],
    isPinned: true,
    isArchived: false,
    syncStatus: 'error',
    createdAt: new Date('2026-03-01T20:00:00Z'),
    updatedAt: new Date('2026-03-23T22:30:00Z'),
  },
  {
    id: 'note-006',
    title: 'Chicken Parmesan Recipe',
    content:
      'Ingredients: Chicken breasts, breadcrumbs, parmesan cheese, marinara sauce...',
    folder: 'Recipes',
    tags: ['cooking', 'dinner', 'italian'],
    isPinned: false,
    isArchived: false,
    syncStatus: 'synced',
    createdAt: new Date('2026-02-28T18:10:00Z'),
    updatedAt: new Date('2026-02-28T18:10:00Z'),
  },
  {
    id: 'note-007',
    title: 'Workout Routine - Spring',
    content:
      'Monday: Upper Body. Wednesday: Lower Body. Friday: Cardio and Core.',
    folder: 'Health',
    tags: ['fitness', 'gym'],
    isPinned: false,
    isArchived: false,
    syncStatus: 'synced',
    createdAt: new Date('2026-03-10T07:00:00Z'),
    updatedAt: new Date('2026-03-15T07:30:00Z'),
  },
  {
    id: 'note-008',
    title: 'Books to Read',
    content:
      '1. Dune by Frank Herbert\n2. Atomic Habits by James Clear\n3. The Three-Body Problem',
    folder: 'Personal',
    tags: ['reading', 'leisure'],
    isPinned: false,
    isArchived: false,
    syncStatus: 'synced',
    createdAt: new Date('2025-12-25T10:00:00Z'),
    updatedAt: new Date('2026-03-18T21:15:00Z'),
  },
  {
    id: 'note-009',
    title: 'Q1 Performance Review Notes',
    content:
      'Hit all major KPIs. Need to focus on mentoring junior devs in Q2.',
    folder: 'Work/HR',
    tags: ['review', 'goals', 'career'],
    isPinned: false,
    isArchived: true,
    syncStatus: 'synced',
    createdAt: new Date('2026-03-05T13:45:00Z'),
    updatedAt: new Date('2026-03-06T09:20:00Z'),
  },
  {
    id: 'note-010',
    title: 'Draft: Blog Post on React Hooks',
    content:
      'Introduction to useEffect and useMemo. Why dependency arrays matter...',
    folder: 'Content Creation',
    tags: ['blog', 'react', 'programming'],
    isPinned: false,
    isArchived: false,
    syncStatus: 'syncing',
    createdAt: new Date('2026-03-21T15:00:00Z'),
    updatedAt: new Date('2026-03-23T23:05:00Z'),
  },
]

export async function getNotes() {
  return notes
}
